// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ActionRequestDto
    {
        /// <summary>
        /// Initializes a new instance of the ActionRequestDto class.
        /// </summary>
        public ActionRequestDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ActionRequestDto class.
        /// </summary>
        public ActionRequestDto(string actionType = default(string), IDictionary<string, string> arguments = default(IDictionary<string, string>), string definitionVersion = default(string), string datasetSnapshotName = default(string), string dataflowJson = default(string), string computeTarget = default(string), string amlComputeVmSize = default(string), IList<string> pipArguments = default(IList<string>))
        {
            ActionType = actionType;
            Arguments = arguments;
            DefinitionVersion = definitionVersion;
            DatasetSnapshotName = datasetSnapshotName;
            DataflowJson = dataflowJson;
            ComputeTarget = computeTarget;
            AmlComputeVmSize = amlComputeVmSize;
            PipArguments = pipArguments;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "actionType")]
        public string ActionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "arguments")]
        public IDictionary<string, string> Arguments { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "definitionVersion")]
        public string DefinitionVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "datasetSnapshotName")]
        public string DatasetSnapshotName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataflowJson")]
        public string DataflowJson { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "computeTarget")]
        public string ComputeTarget { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amlComputeVmSize")]
        public string AmlComputeVmSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pipArguments")]
        public IList<string> PipArguments { get; set; }

    }
}
