// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BatchAddOrModifyRunResultDto
    {
        /// <summary>
        /// Initializes a new instance of the BatchAddOrModifyRunResultDto
        /// class.
        /// </summary>
        public BatchAddOrModifyRunResultDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BatchAddOrModifyRunResultDto
        /// class.
        /// </summary>
        public BatchAddOrModifyRunResultDto(IDictionary<string, RunDto> runs = default(IDictionary<string, RunDto>), IDictionary<string, ErrorResponse> errors = default(IDictionary<string, ErrorResponse>))
        {
            Runs = runs;
            Errors = errors;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "runs")]
        public IDictionary<string, RunDto> Runs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IDictionary<string, ErrorResponse> Errors { get; set; }

    }
}
