// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CreateRunDto
    {
        /// <summary>
        /// Initializes a new instance of the CreateRunDto class.
        /// </summary>
        public CreateRunDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateRunDto class.
        /// </summary>
        public CreateRunDto(string runId = default(string), string parentRunId = default(string), string status = default(string), System.DateTime? startTimeUtc = default(System.DateTime?), System.DateTime? endTimeUtc = default(System.DateTime?), bool? heartbeatEnabled = default(bool?), RunOptions options = default(RunOptions), string name = default(string), string dataContainerId = default(string), string description = default(string), bool? hidden = default(bool?), string runType = default(string), IDictionary<string, string> properties = default(IDictionary<string, string>), string scriptName = default(string), string target = default(string), IDictionary<string, string> tags = default(IDictionary<string, string>), object runDefinition = default(object), CreatedFromDto createdFrom = default(CreatedFromDto), string cancelUri = default(string))
        {
            RunId = runId;
            ParentRunId = parentRunId;
            Status = status;
            StartTimeUtc = startTimeUtc;
            EndTimeUtc = endTimeUtc;
            HeartbeatEnabled = heartbeatEnabled;
            Options = options;
            Name = name;
            DataContainerId = dataContainerId;
            Description = description;
            Hidden = hidden;
            RunType = runType;
            Properties = properties;
            ScriptName = scriptName;
            Target = target;
            Tags = tags;
            RunDefinition = runDefinition;
            CreatedFrom = createdFrom;
            CancelUri = cancelUri;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "runId")]
        public string RunId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentRunId")]
        public string ParentRunId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startTimeUtc")]
        public System.DateTime? StartTimeUtc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endTimeUtc")]
        public System.DateTime? EndTimeUtc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "heartbeatEnabled")]
        public bool? HeartbeatEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "options")]
        public RunOptions Options { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataContainerId")]
        public string DataContainerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hidden")]
        public bool? Hidden { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "runType")]
        public string RunType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scriptName")]
        public string ScriptName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public IDictionary<string, string> Tags { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "runDefinition")]
        public object RunDefinition { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdFrom")]
        public CreatedFromDto CreatedFrom { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cancelUri")]
        public string CancelUri { get; set; }

    }
}
