// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DataPathDto
    {
        /// <summary>
        /// Initializes a new instance of the DataPathDto class.
        /// </summary>
        public DataPathDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataPathDto class.
        /// </summary>
        public DataPathDto(string datastoreName = default(string), string relativePath = default(string), string azureFilePath = default(string), IList<string> paths = default(IList<string>), SqlDataPath sqlDataPath = default(SqlDataPath), IDictionary<string, object> additionalProperties = default(IDictionary<string, object>))
        {
            DatastoreName = datastoreName;
            RelativePath = relativePath;
            AzureFilePath = azureFilePath;
            Paths = paths;
            SqlDataPath = sqlDataPath;
            AdditionalProperties = additionalProperties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "datastoreName")]
        public string DatastoreName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relativePath")]
        public string RelativePath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "azureFilePath")]
        public string AzureFilePath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paths")]
        public IList<string> Paths { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sqlDataPath")]
        public SqlDataPath SqlDataPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "additionalProperties")]
        public IDictionary<string, object> AdditionalProperties { get; set; }

    }
}
