// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DataSourceProperties
    {
        /// <summary>
        /// Initializes a new instance of the DataSourceProperties class.
        /// </summary>
        public DataSourceProperties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataSourceProperties class.
        /// </summary>
        /// <param name="encoding">Possible values include: 'UTF8', 'ISO88591',
        /// 'LATIN1', 'ASCII', 'UTF16', 'UTF32', 'UTF8BOM',
        /// 'WINDOWS1252'</param>
        public DataSourceProperties(string encoding = default(string), string dataSourceType = default(string), string delimiter = default(string), int? skipLinesCount = default(int?), bool? promoteHeaders = default(bool?), int? columnCount = default(int?), IList<int?> columnPositions = default(IList<int?>))
        {
            Encoding = encoding;
            DataSourceType = dataSourceType;
            Delimiter = delimiter;
            SkipLinesCount = skipLinesCount;
            PromoteHeaders = promoteHeaders;
            ColumnCount = columnCount;
            ColumnPositions = columnPositions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'UTF8', 'ISO88591', 'LATIN1',
        /// 'ASCII', 'UTF16', 'UTF32', 'UTF8BOM', 'WINDOWS1252'
        /// </summary>
        [JsonProperty(PropertyName = "encoding")]
        public string Encoding { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataSourceType")]
        public string DataSourceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "delimiter")]
        public string Delimiter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "skipLinesCount")]
        public int? SkipLinesCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "promoteHeaders")]
        public bool? PromoteHeaders { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnCount")]
        public int? ColumnCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnPositions")]
        public IList<int?> ColumnPositions { get; set; }

    }
}
