// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DatasetSnapshotDto
    {
        /// <summary>
        /// Initializes a new instance of the DatasetSnapshotDto class.
        /// </summary>
        public DatasetSnapshotDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DatasetSnapshotDto class.
        /// </summary>
        public DatasetSnapshotDto(string datasetSnapshotName = default(string), System.DateTime? timeStamp = default(System.DateTime?), System.Guid? datasetId = default(System.Guid?), string definitionVersion = default(string), string profileActionId = default(string), DataPathDto dataSnapshotPath = default(DataPathDto), System.DateTime? createdTime = default(System.DateTime?))
        {
            DatasetSnapshotName = datasetSnapshotName;
            TimeStamp = timeStamp;
            DatasetId = datasetId;
            DefinitionVersion = definitionVersion;
            ProfileActionId = profileActionId;
            DataSnapshotPath = dataSnapshotPath;
            CreatedTime = createdTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "datasetSnapshotName")]
        public string DatasetSnapshotName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeStamp")]
        public System.DateTime? TimeStamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "datasetId")]
        public System.Guid? DatasetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "definitionVersion")]
        public string DefinitionVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "profileActionId")]
        public string ProfileActionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataSnapshotPath")]
        public DataPathDto DataSnapshotPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdTime")]
        public System.DateTime? CreatedTime { get; set; }

    }
}
