// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for DeploymentType.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(DeploymentTypeConverter))]
    public struct DeploymentType : System.IEquatable<DeploymentType>
    {
        private DeploymentType(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly DeploymentType GRPCRealtimeEndpoint = "GRPCRealtimeEndpoint";

        public static readonly DeploymentType HttpRealtimeEndpoint = "HttpRealtimeEndpoint";


        /// <summary>
        /// Underlying value of enum DeploymentType
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for DeploymentType
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type DeploymentType
        /// </summary>
        public bool Equals(DeploymentType e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to DeploymentType
        /// </summary>
        public static implicit operator DeploymentType(string value)
        {
            return new DeploymentType(value);
        }

        /// <summary>
        /// Implicit operator to convert DeploymentType to string
        /// </summary>
        public static implicit operator string(DeploymentType e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum DeploymentType
        /// </summary>
        public static bool operator == (DeploymentType e1, DeploymentType e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum DeploymentType
        /// </summary>
        public static bool operator != (DeploymentType e1, DeploymentType e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for DeploymentType
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is DeploymentType && Equals((DeploymentType)obj);
        }

        /// <summary>
        /// Returns for hashCode DeploymentType
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
