// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExcelSection
    {
        /// <summary>
        /// Initializes a new instance of the ExcelSection class.
        /// </summary>
        public ExcelSection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExcelSection class.
        /// </summary>
        public ExcelSection(string sheetName = default(string))
        {
            SheetName = sheetName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sheetName")]
        public string SheetName { get; set; }

    }
}
