// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExperimentDto
    {
        /// <summary>
        /// Initializes a new instance of the ExperimentDto class.
        /// </summary>
        public ExperimentDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExperimentDto class.
        /// </summary>
        public ExperimentDto(System.Guid? experimentId = default(System.Guid?), string name = default(string), string description = default(string), System.DateTime? createdUtc = default(System.DateTime?), System.DateTime? archivedTime = default(System.DateTime?))
        {
            ExperimentId = experimentId;
            Name = name;
            Description = description;
            CreatedUtc = createdUtc;
            ArchivedTime = archivedTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "experimentId")]
        public System.Guid? ExperimentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdUtc")]
        public System.DateTime? CreatedUtc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "archivedTime")]
        public System.DateTime? ArchivedTime { get; set; }

    }
}
