// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The List Usages operation response.
    /// </summary>
    public partial class ListUsagesResult
    {
        /// <summary>
        /// Initializes a new instance of the ListUsagesResult class.
        /// </summary>
        public ListUsagesResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ListUsagesResult class.
        /// </summary>
        /// <param name="value">The list of AML resource usages.</param>
        /// <param name="nextLink">The URI to fetch the next page of AML
        /// resource usage information. Call ListNext() with this to fetch the
        /// next page of AML resource usage information.</param>
        public ListUsagesResult(IList<Usage> value = default(IList<Usage>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the list of AML resource usages.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<Usage> Value { get; private set; }

        /// <summary>
        /// Gets the URI to fetch the next page of AML resource usage
        /// information. Call ListNext() with this to fetch the next page of
        /// AML resource usage information.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; private set; }

    }
}
