// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The requirements for the liveness probe on the service.
    /// </summary>
    public partial class LivenessProbeRequirements
    {
        /// <summary>
        /// Initializes a new instance of the LivenessProbeRequirements class.
        /// </summary>
        public LivenessProbeRequirements()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LivenessProbeRequirements class.
        /// </summary>
        /// <param name="timeoutSeconds">Timeout for the liveness probe in
        /// seconds.</param>
        /// <param name="successThreshold">Success threshold for the liveness
        /// probe in seconds.</param>
        /// <param name="failureThreshold">Failure threshold for the liveness
        /// probe in seconds.</param>
        /// <param name="periodSeconds">Time period for the liveness probe in
        /// seconds.</param>
        /// <param name="initialDelaySeconds">Delay for the liveness probe in
        /// seconds.</param>
        public LivenessProbeRequirements(int? timeoutSeconds = default(int?), int? successThreshold = default(int?), int? failureThreshold = default(int?), int? periodSeconds = default(int?), int? initialDelaySeconds = default(int?))
        {
            TimeoutSeconds = timeoutSeconds;
            SuccessThreshold = successThreshold;
            FailureThreshold = failureThreshold;
            PeriodSeconds = periodSeconds;
            InitialDelaySeconds = initialDelaySeconds;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets timeout for the liveness probe in seconds.
        /// </summary>
        [JsonProperty(PropertyName = "timeoutSeconds")]
        public int? TimeoutSeconds { get; set; }

        /// <summary>
        /// Gets or sets success threshold for the liveness probe in seconds.
        /// </summary>
        [JsonProperty(PropertyName = "successThreshold")]
        public int? SuccessThreshold { get; set; }

        /// <summary>
        /// Gets or sets failure threshold for the liveness probe in seconds.
        /// </summary>
        [JsonProperty(PropertyName = "failureThreshold")]
        public int? FailureThreshold { get; set; }

        /// <summary>
        /// Gets or sets time period for the liveness probe in seconds.
        /// </summary>
        [JsonProperty(PropertyName = "periodSeconds")]
        public int? PeriodSeconds { get; set; }

        /// <summary>
        /// Gets or sets delay for the liveness probe in seconds.
        /// </summary>
        [JsonProperty(PropertyName = "initialDelaySeconds")]
        public int? InitialDelaySeconds { get; set; }

    }
}
