// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MetaApiVersionResponse
    {
        /// <summary>
        /// Initializes a new instance of the MetaApiVersionResponse class.
        /// </summary>
        public MetaApiVersionResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MetaApiVersionResponse class.
        /// </summary>
        public MetaApiVersionResponse(string name = default(string), string version = default(string), IDictionary<string, string> properties = default(IDictionary<string, string>))
        {
            Name = name;
            Version = version;
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

    }
}
