// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Paginated list of Models.
    /// </summary>
    public partial class PaginatedModelList
    {
        /// <summary>
        /// Initializes a new instance of the PaginatedModelList class.
        /// </summary>
        public PaginatedModelList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaginatedModelList class.
        /// </summary>
        /// <param name="value">An array of Model objects.</param>
        /// <param name="nextLink">A continuation link (absolute URI) to the
        /// next page of results in the list.</param>
        public PaginatedModelList(IList<Model> value = default(IList<Model>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets an array of Model objects.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<Model> Value { get; set; }

        /// <summary>
        /// Gets or sets a continuation link (absolute URI) to the next page of
        /// results in the list.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; set; }

    }
}
