// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PaginatedResultDatasetSnapshotDto
    {
        /// <summary>
        /// Initializes a new instance of the PaginatedResultDatasetSnapshotDto
        /// class.
        /// </summary>
        public PaginatedResultDatasetSnapshotDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaginatedResultDatasetSnapshotDto
        /// class.
        /// </summary>
        public PaginatedResultDatasetSnapshotDto(IList<DatasetSnapshotDto> value = default(IList<DatasetSnapshotDto>), string continuationToken = default(string))
        {
            Value = value;
            ContinuationToken = continuationToken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<DatasetSnapshotDto> Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "continuationToken")]
        public string ContinuationToken { get; set; }

    }
}
