// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RunDetailsDto
    {
        /// <summary>
        /// Initializes a new instance of the RunDetailsDto class.
        /// </summary>
        public RunDetailsDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RunDetailsDto class.
        /// </summary>
        public RunDetailsDto(string runId = default(string), string target = default(string), string status = default(string), System.DateTime? startTimeUtc = default(System.DateTime?), System.DateTime? endTimeUtc = default(System.DateTime?), ErrorResponse error = default(ErrorResponse), IList<RunDetailsWarningDto> warnings = default(IList<RunDetailsWarningDto>), IDictionary<string, string> properties = default(IDictionary<string, string>), object runDefinition = default(object), IDictionary<string, string> logFiles = default(IDictionary<string, string>))
        {
            RunId = runId;
            Target = target;
            Status = status;
            StartTimeUtc = startTimeUtc;
            EndTimeUtc = endTimeUtc;
            Error = error;
            Warnings = warnings;
            Properties = properties;
            RunDefinition = runDefinition;
            LogFiles = logFiles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "runId")]
        public string RunId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startTimeUtc")]
        public System.DateTime? StartTimeUtc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endTimeUtc")]
        public System.DateTime? EndTimeUtc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public ErrorResponse Error { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "warnings")]
        public IList<RunDetailsWarningDto> Warnings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "runDefinition")]
        public object RunDefinition { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logFiles")]
        public IDictionary<string, string> LogFiles { get; set; }

    }
}
