// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for UnderlyingResourceAction.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(UnderlyingResourceActionConverter))]
    public struct UnderlyingResourceAction : System.IEquatable<UnderlyingResourceAction>
    {
        private UnderlyingResourceAction(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly UnderlyingResourceAction Delete = "Delete";

        public static readonly UnderlyingResourceAction Detach = "Detach";


        /// <summary>
        /// Underlying value of enum UnderlyingResourceAction
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for UnderlyingResourceAction
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type UnderlyingResourceAction
        /// </summary>
        public bool Equals(UnderlyingResourceAction e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to UnderlyingResourceAction
        /// </summary>
        public static implicit operator UnderlyingResourceAction(string value)
        {
            return new UnderlyingResourceAction(value);
        }

        /// <summary>
        /// Implicit operator to convert UnderlyingResourceAction to string
        /// </summary>
        public static implicit operator string(UnderlyingResourceAction e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum UnderlyingResourceAction
        /// </summary>
        public static bool operator == (UnderlyingResourceAction e1, UnderlyingResourceAction e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum UnderlyingResourceAction
        /// </summary>
        public static bool operator != (UnderlyingResourceAction e1, UnderlyingResourceAction e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for UnderlyingResourceAction
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is UnderlyingResourceAction && Equals((UnderlyingResourceAction)obj);
        }

        /// <summary>
        /// Returns for hashCode UnderlyingResourceAction
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
