// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for VmPriority.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(VmPriorityConverter))]
    public struct VmPriority : System.IEquatable<VmPriority>
    {
        private VmPriority(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly VmPriority Dedicated = "Dedicated";

        public static readonly VmPriority LowPriority = "LowPriority";


        /// <summary>
        /// Underlying value of enum VmPriority
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for VmPriority
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type VmPriority
        /// </summary>
        public bool Equals(VmPriority e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to VmPriority
        /// </summary>
        public static implicit operator VmPriority(string value)
        {
            return new VmPriority(value);
        }

        /// <summary>
        /// Implicit operator to convert VmPriority to string
        /// </summary>
        public static implicit operator string(VmPriority e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum VmPriority
        /// </summary>
        public static bool operator == (VmPriority e1, VmPriority e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum VmPriority
        /// </summary>
        public static bool operator != (VmPriority e1, VmPriority e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for VmPriority
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is VmPriority && Equals((VmPriority)obj);
        }

        /// <summary>
        /// Returns for hashCode VmPriority
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
