// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Events.
    /// </summary>
    public static partial class EventsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The Azure Subscription ID.
            /// </param>
            /// <param name='resourceGroupName'>
            /// Name of the resource group in which the workspace is located.
            /// </param>
            /// <param name='workspaceName'>
            /// The name of the workspace.
            /// </param>
            /// <param name='experimentName'>
            /// </param>
            /// <param name='runId'>
            /// </param>
            /// <param name='filter'>
            /// </param>
            /// <param name='continuationToken'>
            /// </param>
            /// <param name='orderby'>
            /// </param>
            /// <param name='sortorder'>
            /// Possible values include: 'Asc', 'Desc'
            /// </param>
            /// <param name='top'>
            /// </param>
            public static PaginatedBaseEvent List(this IEvents operations, System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, string runId, string filter = default(string), string continuationToken = default(string), IList<string> orderby = default(IList<string>), string sortorder = default(string), int? top = default(int?))
            {
                return operations.ListAsync(subscriptionId, resourceGroupName, workspaceName, experimentName, runId, filter, continuationToken, orderby, sortorder, top).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The Azure Subscription ID.
            /// </param>
            /// <param name='resourceGroupName'>
            /// Name of the resource group in which the workspace is located.
            /// </param>
            /// <param name='workspaceName'>
            /// The name of the workspace.
            /// </param>
            /// <param name='experimentName'>
            /// </param>
            /// <param name='runId'>
            /// </param>
            /// <param name='filter'>
            /// </param>
            /// <param name='continuationToken'>
            /// </param>
            /// <param name='orderby'>
            /// </param>
            /// <param name='sortorder'>
            /// Possible values include: 'Asc', 'Desc'
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PaginatedBaseEvent> ListAsync(this IEvents operations, System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, string runId, string filter = default(string), string continuationToken = default(string), IList<string> orderby = default(IList<string>), string sortorder = default(string), int? top = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ListWithHttpMessagesAsync(subscriptionId, resourceGroupName, workspaceName, experimentName, runId, filter, continuationToken, orderby, sortorder, top, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The Azure Subscription ID.
            /// </param>
            /// <param name='resourceGroupName'>
            /// Name of the resource group in which the workspace is located.
            /// </param>
            /// <param name='workspaceName'>
            /// The name of the workspace.
            /// </param>
            /// <param name='experimentName'>
            /// </param>
            /// <param name='runId'>
            /// </param>
            /// <param name='eventMessage'>
            /// </param>
            public static void Post(this IEvents operations, System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, string runId, BaseEventDto eventMessage = default(BaseEventDto))
            {
                operations.PostAsync(subscriptionId, resourceGroupName, workspaceName, experimentName, runId, eventMessage).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The Azure Subscription ID.
            /// </param>
            /// <param name='resourceGroupName'>
            /// Name of the resource group in which the workspace is located.
            /// </param>
            /// <param name='workspaceName'>
            /// The name of the workspace.
            /// </param>
            /// <param name='experimentName'>
            /// </param>
            /// <param name='runId'>
            /// </param>
            /// <param name='eventMessage'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PostAsync(this IEvents operations, System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, string runId, BaseEventDto eventMessage = default(BaseEventDto), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.PostWithHttpMessagesAsync(subscriptionId, resourceGroupName, workspaceName, experimentName, runId, eventMessage, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The Azure Subscription ID.
            /// </param>
            /// <param name='resourceGroupName'>
            /// Name of the resource group in which the workspace is located.
            /// </param>
            /// <param name='workspaceName'>
            /// The name of the workspace.
            /// </param>
            /// <param name='experimentName'>
            /// </param>
            /// <param name='batchEventCommand'>
            /// </param>
            public static BatchEventCommandResultDto BatchPost(this IEvents operations, System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, BatchEventCommandDto batchEventCommand)
            {
                return operations.BatchPostAsync(subscriptionId, resourceGroupName, workspaceName, experimentName, batchEventCommand).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The Azure Subscription ID.
            /// </param>
            /// <param name='resourceGroupName'>
            /// Name of the resource group in which the workspace is located.
            /// </param>
            /// <param name='workspaceName'>
            /// The name of the workspace.
            /// </param>
            /// <param name='experimentName'>
            /// </param>
            /// <param name='batchEventCommand'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<BatchEventCommandResultDto> BatchPostAsync(this IEvents operations, System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, BatchEventCommandDto batchEventCommand, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.BatchPostWithHttpMessagesAsync(subscriptionId, resourceGroupName, workspaceName, experimentName, batchEventCommand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
