// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// RunMetric operations.
    /// </summary>
    public partial interface IRunMetric
    {
        /// <param name='subscriptionId'>
        /// The Azure Subscription ID.
        /// </param>
        /// <param name='resourceGroupName'>
        /// Name of the resource group in which the workspace is located.
        /// </param>
        /// <param name='workspaceName'>
        /// The name of the workspace.
        /// </param>
        /// <param name='experimentName'>
        /// </param>
        /// <param name='runId'>
        /// </param>
        /// <param name='metricDto'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorResponseException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse> PostWithHttpMessagesAsync(System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, string runId, MetricDto metricDto = default(MetricDto), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <param name='subscriptionId'>
        /// The Azure Subscription ID.
        /// </param>
        /// <param name='resourceGroupName'>
        /// Name of the resource group in which the workspace is located.
        /// </param>
        /// <param name='workspaceName'>
        /// The name of the workspace.
        /// </param>
        /// <param name='experimentName'>
        /// </param>
        /// <param name='runId'>
        /// </param>
        /// <param name='batchMetricDto'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorResponseException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse> PostBatchWithHttpMessagesAsync(System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, string runId, BatchMetricDto batchMetricDto = default(BatchMetricDto), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <param name='subscriptionId'>
        /// The Azure Subscription ID.
        /// </param>
        /// <param name='resourceGroupName'>
        /// Name of the resource group in which the workspace is located.
        /// </param>
        /// <param name='workspaceName'>
        /// The name of the workspace.
        /// </param>
        /// <param name='experimentName'>
        /// </param>
        /// <param name='metricId'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorResponseException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<RunMetricDto>> GetWithHttpMessagesAsync(System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, System.Guid metricId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <param name='subscriptionId'>
        /// The Azure Subscription ID.
        /// </param>
        /// <param name='resourceGroupName'>
        /// Name of the resource group in which the workspace is located.
        /// </param>
        /// <param name='workspaceName'>
        /// The name of the workspace.
        /// </param>
        /// <param name='experimentName'>
        /// </param>
        /// <param name='filter'>
        /// </param>
        /// <param name='continuationToken'>
        /// </param>
        /// <param name='orderby'>
        /// </param>
        /// <param name='sortorder'>
        /// Possible values include: 'Asc', 'Desc'
        /// </param>
        /// <param name='top'>
        /// </param>
        /// <param name='mergestrategytype'>
        /// Possible values include: 'Default', 'None', 'MergeToVector'
        /// </param>
        /// <param name='mergestrategyoptions'>
        /// Possible values include: 'None', 'ReportUnmergedMetricsValues'
        /// </param>
        /// <param name='mergestrategysettingsversion'>
        /// </param>
        /// <param name='mergestrategysettingsselectmetrics'>
        /// Possible values include: 'SelectAll', 'SelectByFirstValueSchema'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorResponseException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<PaginatedRunMetricDto>> ListWithHttpMessagesAsync(System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, string filter = default(string), string continuationToken = default(string), IList<string> orderby = default(IList<string>), string sortorder = default(string), int? top = default(int?), string mergestrategytype = default(string), string mergestrategyoptions = default(string), string mergestrategysettingsversion = default(string), string mergestrategysettingsselectmetrics = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <param name='subscriptionId'>
        /// The Azure Subscription ID.
        /// </param>
        /// <param name='resourceGroupName'>
        /// Name of the resource group in which the workspace is located.
        /// </param>
        /// <param name='workspaceName'>
        /// The name of the workspace.
        /// </param>
        /// <param name='experimentName'>
        /// </param>
        /// <param name='queryParams'>
        /// </param>
        /// <param name='mergestrategytype'>
        /// Possible values include: 'Default', 'None', 'MergeToVector'
        /// </param>
        /// <param name='mergestrategyoptions'>
        /// Possible values include: 'None', 'ReportUnmergedMetricsValues'
        /// </param>
        /// <param name='mergestrategysettingsversion'>
        /// </param>
        /// <param name='mergestrategysettingsselectmetrics'>
        /// Possible values include: 'SelectAll', 'SelectByFirstValueSchema'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorResponseException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<PaginatedRunMetricDto>> GetByQueryWithHttpMessagesAsync(System.Guid subscriptionId, string resourceGroupName, string workspaceName, string experimentName, QueryParamsDto queryParams = default(QueryParamsDto), string mergestrategytype = default(string), string mergestrategyoptions = default(string), string mergestrategysettingsversion = default(string), string mergestrategysettingsselectmetrics = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
