// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.MachineLearning.Services.GeneratedOld
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Usages.
    /// </summary>
    public static partial class UsagesExtensions
    {
            /// <summary>
            /// Gets the current usage information as well as limits for AML resources for
            /// given subscription and location.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Azure subscription identifier.
            /// </param>
            /// <param name='location'>
            /// The location for which resource usage is queried.
            /// </param>
            public static ListUsagesResult List(this IUsages operations, string subscriptionId, string location)
            {
                return operations.ListAsync(subscriptionId, location).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the current usage information as well as limits for AML resources for
            /// given subscription and location.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Azure subscription identifier.
            /// </param>
            /// <param name='location'>
            /// The location for which resource usage is queried.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ListUsagesResult> ListAsync(this IUsages operations, string subscriptionId, string location, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ListWithHttpMessagesAsync(subscriptionId, location, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
